### ISSUE TITLE
Problem having adding extension 

### ISSUE THREAD

**Issue by anubhav14-bit** [MrBoomDeveloper/Awery#68]
Please send the following text to the app developers!

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Tombstone maker: 'xCrash 3.1.0'
Crash type: 'java'
Start time: '2024-06-16T12:20:30.681+0530'
Crash time: '2024-06-16T12:23:29.515+0530'
App ID: 'com.mrboomdev.awery'
App version: '1.0.4-Beta-prod-legacy-release'
Rooted: 'No'
API level: '33'
OS version: '13'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'realme'
Brand: 'realme'
Model: 'RMP2204'
Build fingerprint: 'realme/RMP2204/RE5C6EL1:13/SP1A.210812.016/T.R4T1.1743bc7_1:user/release-keys'
pid: 29947, tid: 29947, name: main  >>> com.mrboomdev.awery <<<

java stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mrboomdev.awery.extensions.ExtensionProvider.hasFeature(int)' on a null object reference
	at com.mrboomdev.awery.ui.fragments.MediaCommentsFragment.lambda$setSource$8(MediaCommentsFragment.java:201)
	at com.mrboomdev.awery.ui.fragments.MediaCommentsFragment$$ExternalSyntheticLambda14.onGotView(D8$$SyntheticClass:0)
	at com.mrboomdev.awery.util.ui.adapter.SingleViewAdapter$BindingSingleViewAdapter.onCreateView(SingleViewAdapter.java:85)
	at com.mrboomdev.awery.util.ui.adapter.SingleViewAdapter.onCreateViewHolder(SingleViewAdapter.java:209)
	at androidx.recyclerview.widget.NestedAdapterWrapper.onCreateViewHolder(NestedAdapterWrapper.java:153)
	at androidx.recyclerview.widget.ConcatAdapterController.onCreateViewHolder(ConcatAdapterController.java:326)
	at androidx.recyclerview.widget.ConcatAdapter.onCreateViewHolder(ConcatAdapter.java:184)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1669)
	at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1523)
	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1431)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:662)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:876)
	at android.view.View.layout(View.java:24031)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3608)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2475)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9592)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1414)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1422)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1049)
	at android.view.Choreographer.doFrame(Choreographer.java:937)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1397)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

logcat:
--------- tail end of log main (/system/bin/logcat -b main -d -v threadtime -t 200 --pid 29947 *:D)
--------- beginning of main
06-16 12:23:23.094 29947 29947 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007d8802c200, mContext=0xb400007e1d638f00
06-16 12:23:23.094 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007e1d9c5900, surface=NULL
06-16 12:23:23.625 29947 29947 D OplusScrollToTopManager: com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity,This DecorView@a607fc0[SettingsActivity] change focus to true
06-16 12:23:23.666 29947 29947 D OplusSystemUINavigationGesture: [GESTURE_SIDE_BAR] swipe from 0
06-16 12:23:23.666 29947 29947 D OplusSystemUINavigationGesture: [GESTURE_SIDE_BAR] Hit Side Bar Region !
06-16 12:23:23.765 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=null, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:23.765 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=com.mrboomdev.awery.ui.activity.settings.SettingsActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:23.767 29947 29961 D VRI[MainActivity]: dispatchAppVisibility visible:true
06-16 12:23:23.775 29947 29947 D VRI[MainActivity]: setWindowStopped stopped:false
06-16 12:23:23.778 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=com.mrboomdev.awery.ui.activity.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:23.787 29947 29947 D BufferQueueConsumer: [](id:74fb00000011,api:0,p:-1,c:29947) connect: controlledByApp=false
06-16 12:23:23.787 29947 29947 E IPCThreadState: attemptIncStrongHandle(94): Not supported
06-16 12:23:23.788 29947 29947 D ViewRootImplExtImpl: setUndequeuedBufferCount: 4
06-16 12:23:23.788 29947 29947 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
06-16 12:23:24.009 29947 29991 D BLASTBufferQueue: [VRI[MainActivity][com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.MainActivity]#17](f:0,a:1) acquireNextBufferLocked size=1200x2000 mFrameNumber=1 applyTransaction=true mTimestamp=39551892133280(auto) mPendingTransactions.size=0 graphicBufferId=128621385613437 transform=0
06-16 12:23:24.010 29947 29991 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
06-16 12:23:24.010 29947 29947 D VRI[MainActivity]: draw finished.
06-16 12:23:24.011 29947 29947 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
06-16 12:23:24.011 29947 29947 D VRI[SettingsActivity]: onFocusEvent false
06-16 12:23:24.074 29947 29947 D VRI[MainActivity]: onFocusEvent true
06-16 12:23:24.139 29947 29947 D OplusSystemUINavigationGesture: [GESTURE_SIDE_BAR] swipe from 1
06-16 12:23:24.139 29947 29947 D OplusSystemUINavigationGesture: [GESTURE_SIDE_BAR] Hit Side Bar Region !
06-16 12:23:24.179 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.190 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.197 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.206 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.215 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.222 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.231 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.238 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.245 29947 30047 D skia    : SkJpegCodec::onGetPixels +
06-16 12:23:24.247 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:24.247 29947 29947 D OplusViewDebugManager: OplusViewDebugManager Constructor android.view.debug.OplusViewDebugManager@9ccd2af [mHasViewDebugProperty true] [mHasMsgDebugProperty false] [DEBUG false] [LIGHT_OS false]
06-16 12:23:24.247 29947 29947 D OplusViewDebugManager: OplusViewDebugManager Constructor android.view.debug.OplusViewDebugManager@6c136bc [mHasViewDebugProperty true] [mHasMsgDebugProperty false] [DEBUG false] [LIGHT_OS false]
06-16 12:23:24.291 29947 30047 D skia    : SkJpegCodec::onGetPixels -
06-16 12:23:24.299 29947 30047 D skia    : SkJpegCodec::onGetPixels +
06-16 12:23:24.325 29947 30047 D skia    : SkJpegCodec::onGetPixels -
06-16 12:23:24.510 29947 29961 D VRI[SettingsActivity]: dispatchAppVisibility visible:false
06-16 12:23:24.519 29947 29947 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007e5c32c800, mContext=0xb400007d86a51ec0
06-16 12:23:24.519 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007cf2868b00, surface=NULL
06-16 12:23:24.525 29947 29947 D BLASTBufferQueue: [VRI[SettingsActivity][com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity]#16](f:0,a:4) destructor()
06-16 12:23:24.525 29947 29947 D BufferQueueConsumer: [VRI[SettingsActivity][com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity]#16(BLAST Consumer)16](id:74fb00000010,api:0,p:-1,c:29947) disconnect
06-16 12:23:24.527 29947 29947 D VRI[SettingsActivity]: setWindowStopped stopped:true
06-16 12:23:24.578 29947 29947 I mrboomdev.awery: Explicit concurrent mark compact GC freed 32351(1324KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 9470KB/18MB, paused 602us,3.221ms total 50.444ms
06-16 12:23:24.579 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007e1d9c5900, surface=NULL
06-16 12:23:24.579 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007e1d9ccc00, surface=NULL
06-16 12:23:24.669 29947 29947 I mrboomdev.awery: Explicit concurrent mark compact GC freed 8888(516KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9018KB/17MB, paused 940us,5.694ms total 84.965ms
06-16 12:23:24.678 29947 29947 D OplusScrollToTopManager: com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity,window dying
06-16 12:23:24.678 29947 29947 D OplusScrollToTopManager: com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity,unregisterSystemUIBroadcastReceiver 
06-16 12:23:24.678 29947 29947 D OplusScrollToTopManager: com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.settings.SettingsActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@e9c9f2
06-16 12:23:24.684 29947 29947 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007e5c32c800, mContext=0xb400007d86a51ec0
06-16 12:23:24.684 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::setSurface: this=0xb400007cf2868b00, surface=NULL
06-16 12:23:25.075 29947 29947 D OplusScrollToTopManager: com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.MainActivity,This DecorView@590881c[MainActivity] change focus to true
06-16 12:23:25.330 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:25.330 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:25.330 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.196 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=null, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:26.196 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=com.mrboomdev.awery.ui.activity.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:26.207 29947 30634 D libMEOW : meow new tls: 0xb400007e1d80d6c0
06-16 12:23:26.208 29947 30634 D libMEOW : applied 1 plugins for [com.mrboomdev.awery]:
06-16 12:23:26.208 29947 30634 D libMEOW :   plugin 1: [libMEOW_gift.so]: 0xb400007e0e922300
06-16 12:23:26.208 29947 30634 D libMEOW : rebuild call chain: 0xb400007d822a4400
06-16 12:23:26.209 29947 30634 D libMEOW : meow delete tls: 0xb400007e1d80d6c0
06-16 12:23:26.264 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.264 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.264 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.274 29947 29947 D WindowManager: Add to mViews: DecorView@7322036[MediaActivity],pkg= com.mrboomdev.awery
06-16 12:23:26.279 29947 29947 D InputEventReceiver: Input log is disabled
06-16 12:23:26.279 29947 29947 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=com.mrboomdev.awery.ui.activity.MediaActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
06-16 12:23:26.280 29947 29947 D VRI[MainActivity]: onFocusEvent false
06-16 12:23:26.280 29947 29947 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@77a960d
06-16 12:23:26.296 29947 29947 D BufferQueueConsumer: [](id:74fb00000012,api:0,p:-1,c:29947) connect: controlledByApp=false
06-16 12:23:26.297 29947 29947 E IPCThreadState: attemptIncStrongHandle(34): Not supported
06-16 12:23:26.299 29947 29947 D ViewRootImplExtImpl: setUndequeuedBufferCount: 4
06-16 12:23:26.303 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.303 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.303 29947 29947 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
06-16 12:23:26.306 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.314 29947 29947 D VRI[MediaActivity]: registerCallbacksForSync syncBuffer=false
06-16 12:23:26.321 29947 29991 D BLASTBufferQueue: [VRI[MediaActivity][com.mrboomdev.awery/com.mrboomdev.awery.ui.activity.MediaActivity]#18](f:0,a:1) acquireNextBufferLocked size=1200x2000 mFrameNumber=1 applyTransaction=true mTimestamp=39554203369895(auto) mPendingTransactions.size=0 graphicBufferId=128621385613444 transform=0
06-16 12:23:26.321 29947 29991 D VRI[MediaActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
06-16 12:23:26.321 29947 29991 W Parcel  : Expecting binder but got null!
06-16 12:23:26.321 29947 29947 D VRI[MediaActivity]: draw finished.
06-16 12:23:26.321 29947 29947 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
06-16 12:23:26.350 29947 29947 D VRI[MediaActivity]: registerCallbacksForSync syncBuffer=false
06-16 12:23:26.362 29947 29991 D VRI[MediaActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=3 didProduceBuffer=true syncBuffer=false
06-16 12:23:26.362 29947 29947 D VRI[MediaActivity]: draw finished.
06-16 12:23:26.430 29947 29947 D VRI[MediaActivity]: onFocusEvent true
06-16 12:23:26.521 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.529 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.555 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.563 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.571 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.579 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.588 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.596 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.605 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.613 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.628 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.638 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.646 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.655 29947 29991 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
06-16 12:23:26.813 29947 30581 D VRI[MainActivity]: dispatchAppVisibility visible:false
06-16 12:23:26.819 29947 29947 D OpenGLRenderer: RenderProxy::destroy: this=0xb400007e196f5c00, mContext=0xb400007d985c0ec0
06-16 12:23:26.819 29947 29991 D OpenGLRenderer: SkiaOpenGLPipeline::set

**Comment by itsmechinmoy** [comment]
Download the latest [alpha](https://GitHub.com/itsmechinmoy/awery-updater/releases/latest)
Remember only anime ext are supported for now
